top_srcdir   = /homes/yhong/MyLink/httpd-2.2.17
top_builddir = /homes/yhong/MyLink/httpd-2.2.17
srcdir       = /homes/yhong/MyLink/httpd-2.2.17/os
builddir     = /homes/yhong/MyLink/httpd-2.2.17/os
VPATH        = /homes/yhong/MyLink/httpd-2.2.17/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
