top_srcdir   = /homes/yhong/MyLink/httpd-2.2.17
top_builddir = /homes/yhong/MyLink/httpd-2.2.17
srcdir       = /homes/yhong/MyLink/httpd-2.2.17/modules/filters
builddir     = /homes/yhong/MyLink/httpd-2.2.17/modules/filters
VPATH        = /homes/yhong/MyLink/httpd-2.2.17/modules/filters

include $(top_srcdir)/build/special.mk

