top_srcdir   = /homes/yhong/MyLink/httpd-2.2.17
top_builddir = /homes/yhong/MyLink/httpd-2.2.17
srcdir       = /homes/yhong/MyLink/httpd-2.2.17/modules/http
builddir     = /homes/yhong/MyLink/httpd-2.2.17/modules/http
VPATH        = /homes/yhong/MyLink/httpd-2.2.17/modules/http

include $(top_srcdir)/build/special.mk

