top_srcdir   = /homes/yhong/MyLink/httpd-2.2.17
top_builddir = /homes/yhong/MyLink/httpd-2.2.17
srcdir       = /homes/yhong/MyLink/httpd-2.2.17/modules/cache
builddir     = /homes/yhong/MyLink/httpd-2.2.17/modules/cache
VPATH        = /homes/yhong/MyLink/httpd-2.2.17/modules/cache

include $(top_srcdir)/build/special.mk

