top_srcdir   = /homes/yhong/MyLink/httpd-2.2.17
top_builddir = /homes/yhong/MyLink/httpd-2.2.17
srcdir       = /homes/yhong/MyLink/httpd-2.2.17/modules/metadata
builddir     = /homes/yhong/MyLink/httpd-2.2.17/modules/metadata
VPATH        = /homes/yhong/MyLink/httpd-2.2.17/modules/metadata

include $(top_srcdir)/build/special.mk

