top_srcdir   = /homes/yhong/MyLink/httpd-2.2.17
top_builddir = /homes/yhong/MyLink/httpd-2.2.17
srcdir       = /homes/yhong/MyLink/httpd-2.2.17/modules/ldap
builddir     = /homes/yhong/MyLink/httpd-2.2.17/modules/ldap
VPATH        = /homes/yhong/MyLink/httpd-2.2.17/modules/ldap
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
