top_srcdir   = /homes/yhong/MyLink/httpd-2.2.17
top_builddir = /homes/yhong/MyLink/httpd-2.2.17
srcdir       = /homes/yhong/MyLink/httpd-2.2.17/server/mpm
builddir     = /homes/yhong/MyLink/httpd-2.2.17/server/mpm
VPATH        = /homes/yhong/MyLink/httpd-2.2.17/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
