top_srcdir   = /homes/yhong/MyLink/httpd-2.2.17
top_builddir = /homes/yhong/MyLink/httpd-2.2.17
srcdir       = /homes/yhong/MyLink/httpd-2.2.17/modules/loggers
builddir     = /homes/yhong/MyLink/httpd-2.2.17/modules/loggers
VPATH        = /homes/yhong/MyLink/httpd-2.2.17/modules/loggers

include $(top_srcdir)/build/special.mk

